const ActionType = {
  CART_INITIAL: 'CART_INITIAL',
  CART_PENDING: 'CART_PENDING',
  CART_SUCCESS: 'CART_SUCCESS',
  CART_FAILED: 'CART_FAILED',

  INCREASE_CART_INITIAL: 'INCREASE_CART_INITIAL',
  INCREASE_CART_PENDING: 'INCREASE_CART_PENDING',
  INCREASE_CART_SUCCESS: 'INCREASE_CART_SUCCESS',
  INCREASE_CART_FAILED: 'INCREASE_CART_FAILED',

  DECREASE_CART_INITIAL: 'DECREASE_CART_INITIAL',
  DECREASE_CART_PENDING: 'DECREASE_CART_PENDING',
  DECREASE_CART_SUCCESS: 'DECREASE_CART_SUCCESS',
  DECREASE_CART_FAILED: 'DECREASE_CART_FAILED',

  DELETE_CART_INITIAL: 'DELETE_CART_INITIAL',
  DELETE_CART_PENDING: 'DELETE_CART_PENDING',
  DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
  DELETE_CART_FAILED: 'DELETE_CART_FAILED',
}
export default ActionType