const ActionType = {
  CART_INITIAL: 'CART_INITIAL',
  CART_PENDING: 'CART_PENDING',
  CART_SUCCESS: 'CART_SUCCESS',
  CART_FAILED: 'CART_FAILED',

  CHANGE_CART_INITIAL: 'CHANGE_CART_INITIAL',
  CHANGE_CART_PENDING: 'CHANGE_CART_PENDING',
  CHANGE_CART_SUCCESS: 'CHANGE_CART_SUCCESS',
  CHANGE_CART_FAILED: 'CHANGE_CART_FAILED',
}
export default ActionType