const ActionType = {
  LOGIN_INITIAL: 'LOGIN_INITIAL',
  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_INITIAL: 'REGISTER_INITIAL',
  REGISTER_PENDING: 'REGISTER_PENDING',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  GUST_TOKEN_PENDING: 'GUST_TOKEN_PENDING',
  GUST_TOKEN_SUCCESS: 'GUST_TOKEN_SUCCESS',
  GUST_TOKEN_FAILED: 'GUST_TOKEN_FAILED',

  REFRESH_TOKEN_INITIAL: 'REFRESH_TOKEN_INITIAL',
  REFRESH_TOKEN_PENDING: 'REFRESH_TOKEN_PENDING',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED',
}
export default ActionType